### ISSUE TITLE
composes order

### ISSUE THREAD

**Issue by sullenor** [css-modules/postcss-modules-extract-imports#131]
Just wanted to add the issue as a reminder. I found unpleasant use case.

Since `extracts-imports` plugin extracts imports as soon as it may find em, this behavior may result in the wrong order or the resulting imports declaration.

For example:

```css
.localA {
  composes: D from './d.css';
}

.localB
{
  composes: F from './f.css';
  composes: D from './d.css';
}
```

transforms into

```css
:import("./d.css") {
  i__imported_D_0: D
}

:import("./f.css") {
  i__imported_F_1: F
}

...

:export {
  localA: _source_localA i__imported_D_0;
  localB: _source_localB i__imported_F_1 i__imported_D_0
}
```

which means, that the contents of the `d.css` will be loader before `f.css`. That may lead to a small collapse for the `.localB` selector in case `F` and `D` contain similar rules.
